// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FooterDocumentDataSlicesSlice = MarqueeSlice;

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * ContactEmail field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contactemail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contactemail: prismic.KeyTextField;

  /**
   * Adress field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.adress
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  adress: prismic.KeyTextField;

  /**
   * logo field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * LinkedinLink field in *footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linkedinlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedinlink: prismic.LinkField;

  /**
   * InstagramLink field in *footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.instagramlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagramlink: prismic.LinkField;

  /**
   * GustLink field in *footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.gustlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  gustlink: prismic.LinkField;

  /**
   * Slice Zone field in *footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | SliderSlice
  | LargeHeadingSlice
  | PlaygroundSlice
  | ProjectsListSlice
  | EmptySpaceSlice
  | SidedHeadingSlice
  | MarqueeSlice
  | CenteredHeadingSlice
  | SectionListSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *nav → NavigationList*
 */
export interface NavDocumentDataNavigationlistItem {
  /**
   * Link field in *nav → NavigationList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.navigationlist[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Content for nav documents
 */
interface NavDocumentData {
  /**
   * NavigationList field in *nav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.navigationlist[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigationlist: prismic.GroupField<
    Simplify<NavDocumentDataNavigationlistItem>
  >;

  /**
   * Logo field in *nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Button Content field in *nav*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.button_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_content: prismic.KeyTextField;

  /**
   * Button Link field in *nav*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_link: prismic.KeyTextField;

  /**
   * Logo Minify field in *nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.logo_minify
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_minify: prismic.ImageField<never>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

type ProjectsDocumentDataSlicesSlice = ProjectsSlice;

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Slice Zone field in *Projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectsDocumentDataSlicesSlice> /**
   * Meta Title field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: projects.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: projects.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomeDocument
  | NavDocument
  | ProjectsDocument;

/**
 * Item in *CenteredHeading → Default → Primary → content*
 */
export interface CenteredHeadingSliceDefaultPrimaryContentItem {
  /**
   * text field in *CenteredHeading → Default → Primary → content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_heading.default.primary.content[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *CenteredHeading → Default → Primary*
 */
export interface CenteredHeadingSliceDefaultPrimary {
  /**
   * content field in *CenteredHeading → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_heading.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<
    Simplify<CenteredHeadingSliceDefaultPrimaryContentItem>
  >;
}

/**
 * Default variation for CenteredHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CenteredHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CenteredHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CenteredHeading*
 */
type CenteredHeadingSliceVariation = CenteredHeadingSliceDefault;

/**
 * CenteredHeading Shared Slice
 *
 * - **API ID**: `centered_heading`
 * - **Description**: CenteredHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CenteredHeadingSlice = prismic.SharedSlice<
  "centered_heading",
  CenteredHeadingSliceVariation
>;

/**
 * Primary content in *EmptySpace → space → Primary*
 */
export interface EmptySpaceSliceDefaultPrimary {
  /**
   * visible field in *EmptySpace → space → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: empty_space.default.primary.visible
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  visible: prismic.BooleanField;

  /**
   * size field in *EmptySpace → space → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: empty_space.default.primary.size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  size: prismic.SelectField<"small" | "medium" | "big">;

  /**
   * color field in *EmptySpace → space → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: empty_space.default.primary.color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  color: prismic.SelectField<"white" | "black" | "green">;
}

/**
 * space variation for EmptySpace Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmptySpaceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmptySpaceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EmptySpace*
 */
type EmptySpaceSliceVariation = EmptySpaceSliceDefault;

/**
 * EmptySpace Shared Slice
 *
 * - **API ID**: `empty_space`
 * - **Description**: EmptySpace
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmptySpaceSlice = prismic.SharedSlice<
  "empty_space",
  EmptySpaceSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *LargeHeading → Default → Primary*
 */
export interface LargeHeadingSliceDefaultPrimary {
  /**
   * Content field in *LargeHeading → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: large_heading.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Align Center field in *LargeHeading → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: large_heading.default.primary.align_center
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  align_center: prismic.BooleanField;

  /**
   * Inverse Color field in *LargeHeading → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: large_heading.default.primary.inverse_color
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  inverse_color: prismic.BooleanField;

  /**
   * Font Size field in *LargeHeading → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: medium
   * - **API ID Path**: large_heading.default.primary.font_size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  font_size: prismic.SelectField<"medium" | "large", "filled">;
}

/**
 * Default variation for LargeHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LargeHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LargeHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LargeHeading*
 */
type LargeHeadingSliceVariation = LargeHeadingSliceDefault;

/**
 * LargeHeading Shared Slice
 *
 * - **API ID**: `large_heading`
 * - **Description**: LargeHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LargeHeadingSlice = prismic.SharedSlice<
  "large_heading",
  LargeHeadingSliceVariation
>;

/**
 * Item in *Marquee → Default → Primary → marquees*
 */
export interface MarqueeSliceDefaultPrimaryMarqueesItem {
  /**
   * text field in *Marquee → Default → Primary → marquees*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.marquees[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Inverse Color field in *Marquee → Default → Primary → marquees*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: marquee.default.primary.marquees[].inverse_color
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  inverse_color: prismic.BooleanField;
}

/**
 * Primary content in *Marquee → Default → Primary*
 */
export interface MarqueeSliceDefaultPrimary {
  /**
   * marquees field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.marquees[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  marquees: prismic.GroupField<
    Simplify<MarqueeSliceDefaultPrimaryMarqueesItem>
  >;

  /**
   * Inverse Background field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: marquee.default.primary.inverse_background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  inverse_background: prismic.BooleanField;
}

/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Marquee*
 */
type MarqueeSliceVariation = MarqueeSliceDefault;

/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee`
 * - **Description**: Marquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSlice = prismic.SharedSlice<
  "marquee",
  MarqueeSliceVariation
>;

/**
 * Item in *Playground → Default → Primary → Devices*
 */
export interface PlaygroundSliceDefaultPrimaryDevicesItem {
  /**
   * Device Type field in *Playground → Default → Primary → Devices*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: playground.default.primary.devices[].device_type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  device_type: prismic.KeyTextField;

  /**
   * Tag Line field in *Playground → Default → Primary → Devices*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: playground.default.primary.devices[].tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Description field in *Playground → Default → Primary → Devices*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: playground.default.primary.devices[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Playground → Default → Primary*
 */
export interface PlaygroundSliceDefaultPrimary {
  /**
   * title field in *Playground → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: playground.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * logo field in *Playground → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: playground.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Devices field in *Playground → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: playground.default.primary.devices[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  devices: prismic.GroupField<
    Simplify<PlaygroundSliceDefaultPrimaryDevicesItem>
  >;
}

/**
 * Default variation for Playground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlaygroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PlaygroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Playground*
 */
type PlaygroundSliceVariation = PlaygroundSliceDefault;

/**
 * Playground Shared Slice
 *
 * - **API ID**: `playground`
 * - **Description**: Playground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlaygroundSlice = prismic.SharedSlice<
  "playground",
  PlaygroundSliceVariation
>;

/**
 * Item in *Projects → Default → Primary → Info*
 */
export interface ProjectsSliceDefaultPrimaryInfoItem {
  /**
   * Value field in *Projects → Default → Primary → Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.info[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;

  /**
   * Description field in *Projects → Default → Primary → Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.info[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Name field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * TagLine field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Skills field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.skills
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  skills: prismic.RichTextField;

  /**
   * Description field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Projects → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Info field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.info[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  info: prismic.GroupField<Simplify<ProjectsSliceDefaultPrimaryInfoItem>>;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

/**
 * Item in *ProjectsList → Default → Primary → ProjectsList*
 */
export interface ProjectsListSliceDefaultPrimaryProjectslistItem {
  /**
   * Image field in *ProjectsList → Default → Primary → ProjectsList*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_list.default.primary.projectslist[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Client field in *ProjectsList → Default → Primary → ProjectsList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_list.default.primary.projectslist[].client
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  client: prismic.KeyTextField;

  /**
   * Technics field in *ProjectsList → Default → Primary → ProjectsList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_list.default.primary.projectslist[].technics
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  technics: prismic.RichTextField;

  /**
   * Video field in *ProjectsList → Default → Primary → ProjectsList*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_list.default.primary.projectslist[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Primary content in *ProjectsList → Default → Primary*
 */
export interface ProjectsListSliceDefaultPrimary {
  /**
   * ProjectsList field in *ProjectsList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_list.default.primary.projectslist[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projectslist: prismic.GroupField<
    Simplify<ProjectsListSliceDefaultPrimaryProjectslistItem>
  >;
}

/**
 * Default variation for ProjectsList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectsList*
 */
type ProjectsListSliceVariation = ProjectsListSliceDefault;

/**
 * ProjectsList Shared Slice
 *
 * - **API ID**: `projects_list`
 * - **Description**: ProjectsList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsListSlice = prismic.SharedSlice<
  "projects_list",
  ProjectsListSliceVariation
>;

/**
 * Item in *SectionList → Default → Primary → list*
 */
export interface SectionListSliceDefaultPrimaryListItem {
  /**
   * value field in *SectionList → Default → Primary → list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_list.default.primary.list[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;

  /**
   * text field in *SectionList → Default → Primary → list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_list.default.primary.list[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *SectionList → Default → Primary*
 */
export interface SectionListSliceDefaultPrimary {
  /**
   * list field in *SectionList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section_list.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<SectionListSliceDefaultPrimaryListItem>>;
}

/**
 * Default variation for SectionList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionList*
 */
type SectionListSliceVariation = SectionListSliceDefault;

/**
 * SectionList Shared Slice
 *
 * - **API ID**: `section_list`
 * - **Description**: SectionList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionListSlice = prismic.SharedSlice<
  "section_list",
  SectionListSliceVariation
>;

/**
 * Item in *SidedHeading → Default → Primary → rows*
 */
export interface SidedHeadingSliceDefaultPrimaryRowsItem {
  /**
   * text field in *SidedHeading → Default → Primary → rows*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sided_heading.default.primary.rows[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *SidedHeading → Default → Primary*
 */
export interface SidedHeadingSliceDefaultPrimary {
  /**
   * rows field in *SidedHeading → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sided_heading.default.primary.rows[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rows: prismic.GroupField<Simplify<SidedHeadingSliceDefaultPrimaryRowsItem>>;

  /**
   * background field in *SidedHeading → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: sided_heading.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<"black" | "white" | "green">;

  /**
   * textColor field in *SidedHeading → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: sided_heading.default.primary.textcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  textcolor: prismic.SelectField<"white" | "black" | "green">;
}

/**
 * Default variation for SidedHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SidedHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SidedHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SidedHeading*
 */
type SidedHeadingSliceVariation = SidedHeadingSliceDefault;

/**
 * SidedHeading Shared Slice
 *
 * - **API ID**: `sided_heading`
 * - **Description**: SidedHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SidedHeadingSlice = prismic.SharedSlice<
  "sided_heading",
  SidedHeadingSliceVariation
>;

/**
 * Item in *Slider → Default → Primary → words*
 */
export interface SliderSliceDefaultPrimaryWordsItem {
  /**
   * word field in *Slider → Default → Primary → words*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.words[].word
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  word: prismic.KeyTextField;
}

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * words field in *Slider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.words[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  words: prismic.GroupField<Simplify<SliderSliceDefaultPrimaryWordsItem>>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavDocument,
      NavDocumentData,
      NavDocumentDataNavigationlistItem,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataSlicesSlice,
      AllDocumentTypes,
      CenteredHeadingSlice,
      CenteredHeadingSliceDefaultPrimaryContentItem,
      CenteredHeadingSliceDefaultPrimary,
      CenteredHeadingSliceVariation,
      CenteredHeadingSliceDefault,
      EmptySpaceSlice,
      EmptySpaceSliceDefaultPrimary,
      EmptySpaceSliceVariation,
      EmptySpaceSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LargeHeadingSlice,
      LargeHeadingSliceDefaultPrimary,
      LargeHeadingSliceVariation,
      LargeHeadingSliceDefault,
      MarqueeSlice,
      MarqueeSliceDefaultPrimaryMarqueesItem,
      MarqueeSliceDefaultPrimary,
      MarqueeSliceVariation,
      MarqueeSliceDefault,
      PlaygroundSlice,
      PlaygroundSliceDefaultPrimaryDevicesItem,
      PlaygroundSliceDefaultPrimary,
      PlaygroundSliceVariation,
      PlaygroundSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimaryInfoItem,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      ProjectsListSlice,
      ProjectsListSliceDefaultPrimaryProjectslistItem,
      ProjectsListSliceDefaultPrimary,
      ProjectsListSliceVariation,
      ProjectsListSliceDefault,
      SectionListSlice,
      SectionListSliceDefaultPrimaryListItem,
      SectionListSliceDefaultPrimary,
      SectionListSliceVariation,
      SectionListSliceDefault,
      SidedHeadingSlice,
      SidedHeadingSliceDefaultPrimaryRowsItem,
      SidedHeadingSliceDefaultPrimary,
      SidedHeadingSliceVariation,
      SidedHeadingSliceDefault,
      SliderSlice,
      SliderSliceDefaultPrimaryWordsItem,
      SliderSliceDefaultPrimary,
      SliderSliceVariation,
      SliderSliceDefault,
    };
  }
}
