// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  centered_heading: dynamic(() => import("./CenteredHeading")),
  empty_space: dynamic(() => import("./EmptySpace")),
  hero: dynamic(() => import("./Hero")),
  large_heading: dynamic(() => import("./LargeHeading")),
  marquee: dynamic(() => import("./Marquee")),
  playground: dynamic(() => import("./Playground")),
  projects: dynamic(() => import("./Projects")),
  projects_list: dynamic(() => import("./ProjectsList")),
  section_list: dynamic(() => import("./SectionList")),
  sided_heading: dynamic(() => import("./SidedHeading")),
  slider: dynamic(() => import("./Slider")),
};
